### PR TITLE
Added possibility to add an audio component

### PR DESCRIPTION
**Pull request by giacomorebonato**
Hi, I was looking for a Piano component for React and I found your library: I really liked it! 😄 

I am also fascinated by the possibilities of [ToneJS](https://tonejs.github.io/) for making sounds and I was trying to find a way to use it nicely with your library.

Do you like the idea?

Cheers.

### CODE REVIEW

**Comment by elizabetdev** [comment]
I really like the idea of having this piano expandable! Hope is merged! 👍

**Comment by guinnberg** [comment]
Sounds very interesting... Looking forward to seeing it into the component's features!

**Comment by lillydinhle** [comment]
Hey @giacomorebonato, sorry for the wait! I missed the notification for your pull request, my bad. 😅

I think that's a wonderful idea though. `ToneJS` looks pretty nifty, and I love the idea of having customizable audio! I'd like to make some minor tweaks before publishing the next version, but I'll do that in the coming days. Thanks a ton for your contributions, they'll be out shortly!

**Comment by giacomorebonato** [comment]
Thanks @lillydinhle . I am really interested in your project :)

**Pull request merged**
